In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
d = pd.read_csv('pima-indians-diabetes.csv')
d.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [3]:
ncn = ['Pregnancies', 'Glucose',	'BloodPressure',	'SkinThickness',	'Insulin',	'BMI',	'DiabetesPedigreeFunction',	'Age',	'Outcome']
d.columns = ncn
d.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3            0      137             40             35      168  43.1   
4            5      116             74              0        0  25.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.351   31        0  
1                     0.672   32        1  
2                     0.167   21        0  
3                     2.288   33        1  
4                     0.201   30        0

In [4]:
d.shape

(767, 9)

In [5]:
d.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [6]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               767 non-null    int64  
 1   Glucose                   767 non-null    int64  
 2   BloodPressure             767 non-null    int64  
 3   SkinThickness             767 non-null    int64  
 4   Insulin                   767 non-null    int64  
 5   BMI                       767 non-null    float64
 6   DiabetesPedigreeFunction  767 non-null    float64
 7   Age                       767 non-null    int64  
 8   Outcome                   767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [7]:
d.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   767.000000  767.000000     767.000000     767.000000  767.000000   
mean      3.842243  120.859192      69.101695      20.517601   79.903520   
std       3.370877   31.978468      19.368155      15.954059  115.283105   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   32.000000   
75%       6.000000  140.000000      80.000000      32.000000  127.500000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  767.000000                767.000000  767.000000  767.000000  
mean    31.990482                  0.471674   33.219035    0.348110  
std      7.889091                  0.331497   11.752296    0.476682  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243500   24.000000    0.000000  
50%     32.000000                  0.371000   29.000000    0.000000  
75%     36.600000                  0.625000   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [8]:
sns.pairplot(d)

In [9]:
d.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [10]:
x = d[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin','BMI', 'DiabetesPedigreeFunction', 'Age']]
y = d.Outcome

In [11]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              1       85             66             29        0  26.6   
1              8      183             64              0        0  23.3   
2              1       89             66             23       94  28.1   
3              0      137             40             35      168  43.1   
4              5      116             74              0        0  25.6   
..           ...      ...            ...            ...      ...   ...   
762           10      101             76             48      180  32.9   
763            2      122             70             27        0  36.8   
764            5      121             72             23      112  26.2   
765            1      126             60              0        0  30.1   
766            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.351   31  
1                       0.672   32  
2                       0.167   21  
3                       2.288   33  
4                       0.201   30  
..                        ...  ...  
762                     0.171   63  
763                     0.340   27  
764                     0.245   30  
765                     0.349   47  
766                     0.315   23  

[767 rows x 8 columns]

In [12]:
y

0      0
1      1
2      0
3      1
4      0
      ..
762    0
763    0
764    0
765    1
766    0
Name: Outcome, Length: 767, dtype: int64

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
scores = cross_val_score(gnb, x, y, cv=5)
scores

array([0.75324675, 0.73376623, 0.74509804, 0.78431373, 0.74509804])

In [15]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
scores1 = cross_val_score(mnb, x, y, cv=5)
scores1

array([0.61688312, 0.59090909, 0.60784314, 0.62091503, 0.52941176])

In [16]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
scores2 = cross_val_score(dt, x, y, cv=5)
scores2

array([0.71428571, 0.68181818, 0.7124183 , 0.77777778, 0.71895425])

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
scores3 = cross_val_score(rf, x, y, cv=5)
np.average(scores3)

0.7745013156777862

In [18]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3)

In [19]:
rf.fit(xtrain,ytrain)
rf.score(xtest,ytest)

0.7316017316017316

In [20]:
import pickle as pk
 
pk.dump(rf, open('mod.pkl','wb'))


model = pk.load(open('mod.pkl', 'rb'))

model.predict([[6,	148,	72,	35,	0,	33.6,	0.627,	50	]])

array([1], dtype=int64)

In [21]:
print(pk.format_version)

4.0
